name: Auto add reviewer

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.actor != 'dependabot[bot]' &&
        github.actor != 'renovate[bot]' &&
        github.actor != 'github-actions[bot]' &&
        github.actor != 'book000'
      }}

    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Add reviewer
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer book000 || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
